### ISSUE TITLE
convert method and parse 

### ISSUE THREAD

**Issue by slz929** [yuefanhao/SuperPoint-SuperGlue-TensorRT#1]
cuda11.2 tensorrt8.2, convert to ONNX find 'if' op in nms branch, then i can not parse (parse return false) this ONNX by TRT, how to deal with that?
![image](https://user-images.githubusercontent.com/17669514/218456742-a3e85a17-41e2-45c1-96ff-b3184078b83e.png)

and difference also here:
![image](https://user-images.githubusercontent.com/17669514/218456821-413458e9-1020-45bf-8546-19f03cda9f5c.png)

**Comment by yuefanhao** [comment]
@slz929 Hi, you can try to upgrade your tensorrt version or use the docker environment I provided.
