### ISSUE TITLE
no keypoints!!!

### ISSUE THREAD

**Issue by zwl995** [yuefanhao/SuperPoint-SuperGlue-TensorRT#10]
Hello, why do I use your sample for superpoint feature extraction? The number of features obtained is 0, and all the data provided in the warehouse is used.

**Comment by yuefanhao** [comment]
@zwl995 Can you provide more information about your problem?

**Comment by zwl995** [comment]
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/57057720/24b8942b-6557-453b-9da3-b9f0f064af05)
我定位到问题出现在这，context_的初始化我没有看到，但是在这里它是false，因此直接返回了false。
根据你提供的CMakeLists我无法编译通，有做修改，最终使用的版本信息如下：

**Comment by zwl995** [comment]
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/57057720/6f972f8f-1862-489e-b366-665458931f58)

我定位到问题出现在这，context_的初始化我没有看到，但是在这里它是false，因此直接返回了false。
根据你提供的CMakeLists我无法编译通，有做修改，最终使用的版本信息如下：
TensorRT-8.4.1.5，cuda11.3，opencv3.2.0

**Comment by zwl995** [comment]
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/57057720/b1a556f0-ae68-420f-a06f-6a1f7fb9f7a2)
Problem solved.

**Comment by zwl995** [comment]
If I want to run on a higher resolution panoramic image will it affect the accuracy?

**Comment by yuefanhao** [comment]
@zwl995 It may increase the number of keypoints detected to produce more matches, but the speed will be lower. I didn't run a detailed experiment.
