### ISSUE TITLE
您好 是不是不一样的GPU engine文件不一样啊。

### ISSUE THREAD

**Issue by lxh131419** [yuefanhao/SuperPoint-SuperGlue-TensorRT#12]
我用您的engine文件就会在 context_ = TensorRTUniquePtr<nvinfer1::IExecutionContext>(engine_->createExecutionContext());
        if (!context_) {
            return false;
        }这一步return false 是不是要自己生成engine文件呢？

**Comment by lxh131419** [comment]
您好 我问题解决了 ![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/115532552/f8f8fbaf-4bd5-4ac1-9753-3d0422314a49) 不过我运行速度特别慢 320×240的两张图要3分钟才能运行完 额。。。

**Comment by lxh131419** [comment]
我的GPU是Nvidia 1060的。。。

**Comment by zwl995** [comment]
我觉得初始化模型耗时长也挺正常，我比较关注是后面的提点和匹配耗时，你有检查有没有用上cuda吗？另外你的显卡好像比较一般，这应该也是一个原因。我跑作者提供的example耗时是正常的，但是我自己写了一个简单demo耗时不太正常（非常奇怪），代码基本一样，因为图片尺寸不是我想要的，所以没有细究，看看作者有空能不能解答下。代码如下：

**Comment by zwl995** [comment]
我觉得初始化模型耗时长也挺正常，我比较关注是后面的提点和匹配耗时，你有检查有没有用上cuda吗？另外你的显卡好像比较一般，这应该也是一个原因。我跑作者提供的example耗时是正常的，但是我自己写了一个简单demo耗时不太正常（非常奇怪），代码基本一样，因为图片尺寸不是我想要的，所以没有细究，看看作者有空能不能解答下。代码如下：`#include <iostream>
#include <chrono>
#include <memory>
#include "utils.h"
#include "super_point.h"
#include "super_glue.h"

int main(int argc, char** argv){
    // read image
    cv::Mat image0 = cv::imread(argv[1], cv::IMREAD_GRAYSCALE);
    cv::Mat image1 = cv::imread(argv[2], cv::IMREAD_GRAYSCALE);
    std::string match_res = "../image/match_res.png";

    // read config from file
    Configs configs("../config/config.yaml", "../weights/");
    int width = configs.superglue_config.image_width;
    int height = configs.superglue_config.image_height;
    cv::resize(image0, image0, cv::Size(width, height));
    cv::resize(image1, image1, cv::Size(width, height));

    // create superpoint detector and superglue matcher
    auto superpoint = std::make_shared<SuperPoint>(configs.superpoint_config);
    auto superglue = std::make_shared<SuperGlue>(configs.superglue_config);

    // build engine
    superpoint->build();
    superglue->build();

    // 
    if(superpoint->build()){
        std::cout<<"superpoint can build!!!"<<std::endl;
    }

    Eigen::Matrix<double, 259, Eigen::Dynamic> feature_points0, feature_points1;
    std::vector<cv::DMatch> superglue_matches;
    
    // infer superpoint
    auto start = std::chrono::high_resolution_clock::now();
    superpoint->infer(image0, feature_points0);
    superpoint->infer(image1, feature_points1);
    auto sp_end = std::chrono::high_resolution_clock::now();
    auto sp_times = std::chrono::duration_cast<std::chrono::milliseconds>(sp_end - start);
    std::cout<<"superpoint use times is: "<< sp_times.count() << "ms" << std::endl;

    // infer superglue
    superglue->matching_points(feature_points0, feature_points1, superglue_matches);
    auto sg_end = std::chrono::high_resolution_clock::now();

    auto sg_times = std::chrono::duration_cast<std::chrono::milliseconds>(sg_end - sp_end);
    std::cout<<"superglue use times is: "<<sg_times.count()<< "ms" << std::endl;

    // keypoint transform to cv format
    std::vector<cv::KeyPoint> keypoints0, keypoints1;
    for(size_t i = 0; i < feature_points0.cols(); ++i){
        double score = feature_points0(0, i);
        double x = feature_points0(1, i);
        double y = feature_points0(2, i);
        keypoints0.emplace_back(x, y, 8, -1, score);
    }
    for(size_t i = 0; i < feature_points1.cols(); ++i){
        double score = feature_points1(0, i);
        double x = feature_points1(1, i);
        double y = feature_points1(2, i);
        keypoints1.emplace_back(x, y, 8, -1, score);
    }

    std::cout<<"image0 keypoints size is: "<< keypoints0.size()<<std::endl;
    std::cout<<"image1 keypoints size is: "<< keypoints1.size()<<std::endl;
    std::cout<<"superglue matches size is: "<< superglue_matches.size()<<std::endl;


    // draw matches
    cv::Mat match_image;
    cv::drawMatches(image0, keypoints0, image1, keypoints1, superglue_matches, match_image);
    // cv::imwrite(match_res, match_image);
    cv::imshow("match_image", match_image);
    cv::waitKey(-1);
}`

**Comment by zwl995** [comment]
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/57057720/e335cac6-a672-4e5e-b0f6-bb4a93a7e6c5)

**Comment by lxh131419** [comment]
您好感谢回复 应该是没有用显卡 这个显卡使用率是0 那应该怎么让显卡工作呢？![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/115532552/656c2d96-8b63-4dcb-afa7-3bad1c49ed94)我得跑3分钟才能算完，应该是在cpu上跑的

**Comment by zwl995** [comment]
不是很清楚，我是在服务器上跑的，你可以检查一下TensorRT、cuda、cudnn这些的版本对应，TensorRT这一块我也不太懂

**Comment by lxh131419** [comment]
好吧 多谢您。我再试试。
