### ISSUE TITLE
KTM assertion failure:

### ISSUE THREAD

**Issue by Lachiven** [yuefanhao/SuperPoint-SuperGlue-TensorRT#14]
./superpointglue_image  ../config/config.yaml ../weights/ ${PWD}/../image/image0.png ${PWD}/../image/image1.png
Config file is ../config/config.yaml
First image size: 320x240
Second image size: 320x240
Building inference engine......
KTM assertion failure: /root/gpgpu/MachineLearning/myelin/src/compiler/kernel_timing_model/src/timingModel.cpp:399  dramBandwidth > 0
[1]    102964 abort (core dumped)  ./superpointglue_image ../config/config.yaml ../weights/  
这个怎么解啊。。 感谢
方便加下微信不。。

**Comment by yuefanhao** [comment]
@Lachiven Has the problem been solved? You can contact me by email to discuss more details. yuefan.hao@outlook.com
