### ISSUE TITLE
keypoints detected, no matches?

### ISSUE THREAD

**Issue by Mediumcore** [yuefanhao/SuperPoint-SuperGlue-TensorRT#15]
![2](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/16093691/5440de7d-c665-4930-ae18-47b6dcd298ee)

**Comment by Mediumcore** [comment]
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/16093691/bdefb3ac-9976-443b-9b24-2b74a4373810)
superglue inference result wrong.

**Comment by Mediumcore** [comment]
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/16093691/ae388c2e-ac7b-4beb-916d-929fd64f0051)
Double checked trt in process_output ,trt output error.

**Comment by yuefanhao** [comment]
@Mediumcore I only tested it in the TensorRT 8.4.1.5 environment and recommend using the provided docker environment for now. A subsequent version of the code using the latest Tensorrt version may be updated. Thank you.

**Comment by Mediumcore** [comment]
Thank you for reply detailed，nice work appreciated，i will downgrade trt version for now. Good luck for you.

**Comment by Alex-Beh** [comment]
Same thing happened on my side. I downgraded the TensorRT to version 8.5.1-1 and managed to get the expected output on Ubuntu 22.04.

Another thing is initially it failed during build engine. Then I tried to use gdb to debug and it generate the engine successfully.
