### ISSUE TITLE
Super point + BF matcher

### ISSUE THREAD

**Issue by saimouli** [yuefanhao/SuperPoint-SuperGlue-TensorRT#16]
Would it possible to use classical matching pipeline? I have played with the output from superpoint, but not sure the data structure how the features are stored

**Comment by yuefanhao** [comment]
@saimouli Yes, you can try to use the classical matching pipeline. The feature output of each image is a 259xN matrix, where N is the number of feature points, the first dimension of 259 dimensions is the score, and the second and third dimensions are the location of the feature points. The remaining 256 dimensions are the descriptor information.
