### ISSUE TITLE
Error in SuperPoint building engine

### ISSUE THREAD

**Issue by Zsy103** [yuefanhao/SuperPoint-SuperGlue-TensorRT#17]
```shell
root@1a88e71715e9:/workspace/SuperPoint-SuperGlue-TensorRT/build# ./superpointglue_image  ../config/config.yaml ../weights/ ${PWD}/../image/image0.png ${PWD}/../image/image1.png
Config file is ../config/config.yaml
model_dir: ../weights/superpoint_v1_sim_int32.onnx
First image size: 320x240
Second image size: 320x240
Building inference engine......
False at plan
Error in SuperPoint building engine. Please check your onnx model path.
```

The environment used is the provided Docker. But I encountered the above problem. I am certain that the path of the model is correct. I have modified the code of superpoint.cpp as follows:
```diff
TensorRTUniquePtr<IHostMemory> plan{builder->buildSerializedNetwork(*network, *config)};
    if (!plan) {
+       std::cout << "False at plan\n";
        return false;
    }
```
So what should I do to solve this problem？

**Comment by yuefanhao** [comment]
@Zsy103 I haven't had this kind of problem. What GPU are you using? Let me see if I can reproduce it.

**Comment by Zsy103** [comment]
> 

NVIDIA RTX 4090

**Comment by yuefanhao** [comment]
@Zsy103 There may be a problem with this version of TensorRT working on 4090.

**Comment by supersupercoconut** [comment]
I encounter the same error using Nvidia 4090

**Comment by aniatt** [comment]
I've encountered the same issue on NVIDIA 3050

**Comment by supersupercoconut** [comment]
> I've encountered the same issue on NVIDIA 3050

I solved this problem by updating the version of TensorRT

**Comment by aniatt** [comment]
I'm currently using TensorRT 8.4.1.5. Do you know which TensorRT version has success?

**Comment by supersupercoconut** [comment]
> I'm currently using TensorRT 8.4.1.5. Do you know which TensorRT version has success?

I'm using the TensorRT 8.6 in docker with cuda 11.8 on Nvidia 4090
