### ISSUE TITLE
能否使用 TensorRT 的 Dynamic Shapes功能，处理可变尺寸的输入？

### ISSUE THREAD

**Issue by zxw0919** [yuefanhao/SuperPoint-SuperGlue-TensorRT#18]
我注意到博主说如果图像尺寸不是320*240的话，需要重新生成engine，更改config文件，那么我有个问题想咨询博主，是否可以通过 TensorRT 的 Dynamic Shapes 功能，处理可变尺寸的输入？这个功能能适配于superglue吗？感谢解答！

**Comment by yuefanhao** [comment]
@zxw0919 可以的，我已经完成了这个功能，后续可能会更新代码

**Comment by Nathanyaowu** [comment]
> @zxw0919 可以的，我已经完成了这个功能，后续可能会更新代码

博主什么时候更新呢？

**Comment by Nothingzl** [comment]
@yuefanhao 博主求更新
