### ISSUE TITLE
How to adapt for different image size

### ISSUE THREAD

**Issue by FatihDemirtas** [yuefanhao/SuperPoint-SuperGlue-TensorRT#19]
_Thank you for your excellent work._ 

I want to match two different images. One is taken from camera, other one is taken from somewhere else. So images have different size. I modified the code, but I take an error below;
 
![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/50075805/f4c3b839-4e25-4384-a6e8-2d12c993beb5)

Is there any suggestion?

**Comment by hdrive** [comment]
> _Thank you for your excellent work._
> 
> I want to match two different images. One is taken from camera, other one is taken from somewhere else. So images have different size. I modified the code, but I take an error below;
> 
> ![image](https://private-user-images.githubusercontent.com/50075805/268895387-f4c3b839-4e25-4384-a6e8-2d12c993beb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODA4NjMsIm5iZiI6MTcxNTU4MDU2MywicGF0aCI6Ii81MDA3NTgwNS8yNjg4OTUzODctZjRjM2I4MzktNGUyNS00Mzg0LWE2ZTgtMmQxMmM5OTNiZWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MmY1ODAzMzcyZjNlOGE4ZjU1OTNjOGY3ZTQ3NzhiNDEwMjU4ODg5YTBiMzkwMTA2NDA5NWJhM2NhMjViNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQ2_FUfdXWhzHK4-VUI37stUSpyD-zXeR5cNbeY_kh4)
> 
> Is there any suggestion?

hi, i got the same error, how do you solve the problem? thanks~
