### ISSUE TITLE
Vs2019运行提示失败

### ISSUE THREAD

**Issue by lxh131419** [yuefanhao/SuperPoint-SuperGlue-TensorRT#20]
您好 我vs2015上面可以正常运行，在vs2019上面 auto builder=TensorRTUniquePtr<nvinfer1::IBuilder>(nvinfer1::createInferBuilder(blogger.getTRLogger()); 这一步结果是empty  请问是因为模型和vs2019不兼容吗

**Comment by yuefanhao** [comment]
@lxh131419 你好，我没有在VS上跑过，没有办法给你提供建议，抱歉。

**Comment by oUp2Uo** [comment]
> 您好 我vs2015上面可以正常运行，在vs2019上面 auto builder=TensorRTUniquePtrnvinfer1::IBuilder(nvinfer1::createInferBuilder(blogger.getTRLogger()); 这一步结果是empty 请问是因为模型和vs2019不兼容吗

您好，请问vs2015您是怎么编译过去的？我编译了半天好多错误

**Comment by lxh131419** [comment]
就是提示哪里有问题就增加头文件和库，你要是需要我可以发你一份，不过dll那些太大了 需要你自己去配置&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: oUp2Uo ***@***.***&gt;
发送时间: 2023年11月16日 16:55
收件人: yuefanhao/SuperPoint-SuperGlue-TensorRT ***@***.***&gt;
抄送: lxh131419 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [yuefanhao/SuperPoint-SuperGlue-TensorRT] Vs2019运行提示失败 (Issue #20)





  
您好 我vs2015上面可以正常运行，在vs2019上面 auto builder=TensorRTUniquePtrnvinfer1::IBuilder(nvinfer1::createInferBuilder(blogger.getTRLogger()); 这一步结果是empty 请问是因为模型和vs2019不兼容吗
  
您好，请问vs2015您是怎么编译过去的？我编译了半天好多错误

**Comment by lxh131419** [comment]
我现在最在意的点就是他接你打球。除此以外没有别的。



发自我的iPhone
