### ISSUE TITLE
Why the first Image pair takes much longer time(like 5 seconds) than other pairs??

### ISSUE THREAD

**Issue by zxw0919** [yuefanhao/SuperPoint-SuperGlue-TensorRT#23]
I ran the code on Jetson AGX Orin. And I noticed that  the first image pair always took much longer time(like 5 seconds!)to infer. Do you know the reason? Thanks a lot!

**Comment by yuefanhao** [comment]
@zxw0919 Since some initialization is required before inference can be performed, you can pre-initialize by adjusting the process, this is just an example, and there are many other optimizations that can be made.
