### ISSUE TITLE
No results on superglue

### ISSUE THREAD

**Issue by chenscottus** [yuefanhao/SuperPoint-SuperGlue-TensorRT#27]
Hi,

    I got the superpoints but after superglue, it show nothing as indices0 and indices1 all -1, 

    I compiled and run in Windows 11, CUDA 12.3, TensorRT 8.6.1.6 with the same images and models.

    Thanks

-Scott

**Comment by chenscottus** [comment]
onnxruntime has the results but not the TensorRT.

**Comment by chenscottus** [comment]
This will fix the issue:
inline int64_t volume(const nvinfer1::Dims& d)
{
	if(d.d + d.nbDims < d.d) 
		return std::accumulate(d.d, d.d, 1, std::multiplies<int64_t>());
	else
		return std::accumulate(d.d, d.d + d.nbDims, 1, std::multiplies<int64_t>());
}

**Comment by chenscottus** [comment]
I found the issue, for the multiple outputs, the order of them are different between onnx and tensorrt. You have to use name to find the index.

Thanks,

**Comment by eshafeeqe** [comment]
Hi @chenscottus, 

can you elaborate more about this issue, how you fixed it. I also ended up same issue.

**Comment by chenscottus** [comment]
For example, 

![image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/5216043/bedfc467-0cc4-4970-b4b1-6eb2261ff223)

There are 6 outputs, you cannot assume kpts0, kpts1, ..., mscores1 will be output in order, you show use the name to get the datapointer.

**Comment by eshafeeqe** [comment]
Hi Thanks a lot for your reply. 

It look like you also trying to get these models to tensorrt. Can I chat with you regarding this through may be email? My email id is eshafeeqe@gmail.com

**Comment by chenscottus** [comment]
You can get the models from 
    https://github.com/fabio-sim/LightGlue-ONNX/releases/tag/v0.1.3 
    https://github.com/PINTO0309/LightGlue-ONNX

They both support TensorRT.

And you need to prepare the input images in the correct way.

For example, 
     1) if it is not RGB, you need to convert to RGB
            cv::cvtColor(img_org, img_rgb, cv::COLOR_BGR2RGB);
 
    2) if it is not gray, you need to do that as well
            cv::cvtColor(img_rgb, img_gray, cv::COLOR_RGB2GRAY);
 
    3) it is not CV_32F, normally they should be  CV_8U . You need to convert them too
          img_gray.convertTo(img_model, CV_32F, 1.0 / 255.0);

    If you understand TensorRT, then it should work.

    Good luck!

   -Scott
