### ISSUE TITLE
Superglue no matcher result

### ISSUE THREAD

**Issue by weihaoysgs** [yuefanhao/SuperPoint-SuperGlue-TensorRT#29]
@yuefanhao Hi, thank you for your great work!!!

![match_image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/80088713/85a5efee-aa9e-49b7-a78e-505a3501e18e)

i can get the superpoint result, but there is no matcher result, i have found in other issue, mean that the tensorrt version is too hight, but because of other application using high tensorrt version, so i can not downgrading the tensorrt version.

I'm guessing whether the program can be modified to adapt to a higher version of Tensorrt?

**Comment by yuefanhao** [comment]
It should be the problem of tensorrt version, but I'm sorry that I don't have much time to do this work at present, and I may be compatible with the latest tensorrt version in the future.
