### ISSUE TITLE
About unable to Failed when extracting features from images

### ISSUE THREAD

**Issue by rrryy39** [yuefanhao/SuperPoint-SuperGlue-TensorRT#3]
Hi, I installed the libs and now can correctly make the project but I run into problem that It cannot extracting features from any images. it will say:
Config file is ../config/config.yaml
First image size: 320x240
Second image size: 320x240
Building inference engine......
SuperPoint and SuperGlue inference engine build success.
SuperPoint and SuperGlue test in 100 times.
---------------------------------------------------------
Failed when extracting features from first image.

could you help me on this? thanks

**Comment by rrryy39** [comment]
it is this line throwing false statement
![image](https://user-images.githubusercontent.com/72050785/221382257-d161c2aa-0dba-47d9-b6ca-65e67aae6228.png)

**Comment by rrryy39** [comment]
my cuda version is 11.6 and my tensorRT version is 8.4

**Comment by yuefanhao** [comment]
@rrryy39 Hi, you can delete the old engine file and rerun it to generate the new engine file automatically.
