### ISSUE TITLE
是否用到图像的内参呢

### ISSUE THREAD

**Issue by OpenAskDragon** [yuefanhao/SuperPoint-SuperGlue-TensorRT#31]
您好，我没有看到config文件中包含图像内参信息，难道这个提取和匹配过程不需要图像内参吗，比如去畸变等操作

**Comment by yuefanhao** [comment]
@NirvanaDragon 我用的图片是默认去畸变后的，你直接在去完畸变的图上操作就可以。

**Comment by OpenAskDragon** [comment]
ok，感谢！！
