### ISSUE TITLE
您好，请问解决了高版本tensorrt无法进行superglue匹配的问题了吗

### ISSUE THREAD

**Issue by OpenAskDragon** [yuefanhao/SuperPoint-SuperGlue-TensorRT#32]

**Comment by supersupercoconut** [comment]
I install the tensorRT 8.6.1 with cuda 11.8 and cudnn 8.9(docker nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04) and opencv4.2.0, then I run this code using nvidia RTX 4090. The running time of superpoint is 0.01ms and running time of superglue is 3ms(The test method is same with this code, that is running feature points detection and matching in 100 times but just load image in 1 times, which may get a fast result)

**Comment by OpenAskDragon** [comment]
您好，我采用了您的方案，但是我这边只能用RTX4060Laptop，我的环境为TensorRT-8.6.1.6、cuda-11.8、cudnn 8.9，最终还是不能进行superglue的匹配，但是我将Tensorrt的版本降到8.5.1.7，匹配可以正常运行，如下图所示
![match_image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/117355124/aab5665f-b719-4bc3-b95f-469848cf1aad)

**我有一个问题，就是如果我改变了图片的尺寸，那么我就需要重新生成engine吗，这个生成的过程真的超级慢**

还有我的推理时间如下所示：
First image feature points number: 433
First image infer cost 12.0606 MS
Second image feature points number: 457
Second image infer cost 12.202 MS
Match image cost 17.3333 MS
**这个时间正常吗**

**Comment by supersupercoconut** [comment]
Tensor8.5应该与8.6都是支持40系列的，我第一次安装的时候用的就是8.5.1.7，但是整个系统卡死了。我没有打断点来判断是哪里出问题了，直接找了8.6的tensorRT，然后把docker的cudnn换为了8.9(一开始的docker是8.6的cudnn)。至于运行时间 我感觉不太正常，跟我差的有点多(我的也够离谱的)，你是运行100次之后的结果么。或者可以加微信讨论一下(我的CSDN博客名是Super_coconut，咱私聊就可以加微信了，我也是一个初学者)。我在作者的100次的for循环里面加了一个重新读取图片的操作之后，这样每一次superpoint推理的时间就变成了2ms(很神奇，因为我没有计算读取图片的时间)。如果每一次只推理一张图片，或者只匹配一次的时间是20ms与500ms，这种情况可能是因为单次操作加载模型什么的比较废时间。

**Comment by supersupercoconut** [comment]
Tensor8.5应该与8.6都是支持40系列的，我第一次安装的时候用的就是8.5.1.7，但是整个系统卡死了。我没有打断点来判断是哪里出问题了，直接找了8.6的tensorRT，然后把docker的cudnn换为了8.9(一开始的docker是8.6的cudnn)。至于运行时间 我感觉不太正常，跟我差的有点多(我的也够离谱的)，你是运行100次之后的结果么。或者可以加微信讨论一下(我的CSDN博客名是Super_coconut，咱私聊就可以加微信了，我也是一个初学者)。我在作者的100次的for循环里面加了一个重新读取图片的操作之后，这样每一次superpoint推理的时间就变成了2ms(很神奇，因为我没有计算读取图片的时间)。如果每一次只推理一张图片，或者只匹配一次的时间是20ms与500ms，这种情况可能是因为单次操作加载模型什么的比较废时间。

这是我的执行结果，看起来匹配的结果要比你的好一点
![match_image](https://github.com/yuefanhao/SuperPoint-SuperGlue-TensorRT/assets/137087582/664c45a2-ad4c-4e50-a920-f6378bf400c1)

**Comment by OpenAskDragon** [comment]
> Tensor8.5应该与8.6都是支持40系列的，我第一次安装的时候用的就是8.5.1.7，但是整个系统卡死了。我没有打断点来判断是哪里出问题了，直接找了8.6的tensorRT，然后把docker的cudnn换为了8.9(一开始的docker是8.6的cudnn)。至于运行时间 我感觉不太正常，跟我差的有点多(我的也够离谱的)，你是运行100次之后的结果么。或者可以加微信讨论一下(我的CSDN博客名是Super_coconut，咱私聊就可以加微信了，我也是一个初学者)。我在作者的100次的for循环里面加了一个重新读取图片的操作之后，这样每一次superpoint推理的时间就变成了2ms(很神奇，因为我没有计算读取图片的时间)。如果每一次只推理一张图片，或者只匹配一次的时间是20ms与500ms，这种情况可能是因为单次操作加载模型什么的比较废时间。
> 
> 这是我的执行结果，看起来匹配的结果要比你的好一点 ![match_image](https://private-user-images.githubusercontent.com/137087582/320832278-664c45a2-ad4c-4e50-a920-f6378bf400c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzE1NDMsIm5iZiI6MTcxMjY3MTI0MywicGF0aCI6Ii8xMzcwODc1ODIvMzIwODMyMjc4LTY2NGM0NWEyLWFkNGMtNGU1MC1hOTIwLWY2Mzc4YmY0MDBjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNDAwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmQ0ZGIxZWQ5YzUxNjRkMTM1ZDkxZmFlNjQ0ZDE0YzEwNDg0OTkxOTUzMWMxMGFiODcxNzIyNGRkODg3OGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UL_c-S_eyBiFUJrxlHOvpGxGEZFIgbiAdXVhi1v-Tho)

您好，我在CSDN私聊您了
