### ISSUE TITLE
Why put the post-processing on the cpu side?

### ISSUE THREAD

**Issue by cbbhuxx** [yuefanhao/SuperPoint-SuperGlue-TensorRT#35]
Hi, I see that when you export the onnx file for superpoint/superglue, there are some post-processing commented out. However is there a reason for putting these postprocesses to run on the cpu? Is it because the postprocessing export will be unsupported by the arithmetic, or is it faster to run it on the cpu side?

**Comment by yuefanhao** [comment]
@cbbhuxx some operators are unsupported by tensorrt in old version.

**Comment by cbbhuxx** [comment]
Oh, well, thanks for the answer.
