### ISSUE TITLE
Apply on video.

### ISSUE THREAD

**Issue by Mouaazranjha2** [yuefanhao/SuperPoint-SuperGlue-TensorRT#4]
Hey! i am new to TensorRT. I am working on jetson agx xavier. Can you provide me code for applying these two algorithms on video (offline or via webcam). Thanks.

**Comment by yuefanhao** [comment]
@Mouaazranjha2 Hi, I don't have much time to develop some new features, but you can leave your contact information and I will contact you to get some details about your question.

**Comment by yuefanhao** [comment]
@Mouaazranjha2 Hi, if you have no more questions, I will close this topic.
