### ISSUE TITLE
the input format and out format not match the onnx when using C++ load onnx model

### ISSUE THREAD

**Issue by ChristoCai** [yuefanhao/SuperPoint-SuperGlue-TensorRT#43]
onnxruntime inference try to use GPU Device
input_nodes_num:1
output_nodes_num:2
input format: 1x-1x-1
output format: -1x-1
output format: -1x256

![image](https://github.com/user-attachments/assets/74fe5b07-32e0-4356-a3aa-f21969195dcb)

**Comment by Chriost** [comment]
solved
